// This file can be included several times.

#ifndef MACRO_CONFIG_INT
#error "The config macros must be defined"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Flags, Desc) ;
#define MACRO_CONFIG_COL(Name, ScriptName, Def, Flags, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Flags, Desc) ;
#endif

// Pasta menu state
MACRO_CONFIG_INT(PastaAvoidMode, pasta_avoid_mode, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Selected avoid mode")

// Aimbot
MACRO_CONFIG_INT(PastaAimbot, pasta_aimbot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Pasta aimbot")
MACRO_CONFIG_INT(PastaAimbotDrawFov, pasta_aimbot_draw_fov, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw aimbot fov")
MACRO_CONFIG_INT(PastaAimbotTargetBox, pasta_aimbot_target_box, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw target box")
MACRO_CONFIG_INT(PastaAimbotTargetGlow, pasta_aimbot_target_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw target glow")
MACRO_CONFIG_INT(PastaAimbotAutoShoot, pasta_aimbot_autoshoot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shoot")
MACRO_CONFIG_INT(PastaAimbotAutoHookKey, pasta_aimbot_autohook_key, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aimbot auto hook key state")
MACRO_CONFIG_INT(PastaAimbotAutoShootKey, pasta_aimbot_autoshoot_key, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aimbot auto shoot key state")
MACRO_CONFIG_INT(PastaAimbotPerfectSilent, pasta_aimbot_perfect_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Perfect silent")
MACRO_CONFIG_INT(PastaAimbotAdvancedSettings, pasta_aimbot_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show advanced aimbot settings")
MACRO_CONFIG_INT(PastaAimbotTargetPriority, pasta_aimbot_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aimbot target priority")
MACRO_CONFIG_INT(PastaAimbotSilent, pasta_aimbot_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Global silent")
MACRO_CONFIG_INT(PastaAimbotIgnoreFriends, pasta_aimbot_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ignore friends")
MACRO_CONFIG_COL(PastaAimbotWeaponGlowColor, pasta_aimbot_weapon_glow_color, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Weapon glow color")
MACRO_CONFIG_COL(PastaAimbotHookGlowColor, pasta_aimbot_hook_glow_color, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook glow color")
MACRO_CONFIG_INT(PastaAimbotGrenadeMovePrediction, pasta_aimbot_grenade_move_prediction, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade move prediction")
MACRO_CONFIG_INT(PastaAimbotEdgeAccuracy, pasta_aimbot_edge_accuracy, 8, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Edge accuracy")
MACRO_CONFIG_INT(PastaAimbotMinShootDelay, pasta_aimbot_min_shoot_delay, 1, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Min shoot delay")
MACRO_CONFIG_INT(PastaAimbotMaxShootDelay, pasta_aimbot_max_shoot_delay, 8, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Max shoot delay")

MACRO_CONFIG_INT(PastaAimbotHook, pasta_aimbot_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook aimbot")
MACRO_CONFIG_INT(PastaAimbotHookFov, pasta_aimbot_hook_fov, 30, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook aimbot fov")
MACRO_CONFIG_INT(PastaAimbotHookTargetPriority, pasta_aimbot_hook_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook target priority")
MACRO_CONFIG_INT(PastaAimbotHookSilent, pasta_aimbot_hook_silent, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook silent")
MACRO_CONFIG_INT(PastaAimbotHookIgnoreFriends, pasta_aimbot_hook_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook ignore friends")
MACRO_CONFIG_INT(PastaAimbotHookAccuracy, pasta_aimbot_hook_accuracy, 8, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook accuracy")

MACRO_CONFIG_INT(PastaAimbotHammer, pasta_aimbot_hammer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer aimbot")
MACRO_CONFIG_INT(PastaAimbotHammerFov, pasta_aimbot_hammer_fov, 90, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer aimbot fov")
MACRO_CONFIG_INT(PastaAimbotHammerTargetPriority, pasta_aimbot_hammer_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer target priority")
MACRO_CONFIG_INT(PastaAimbotHammerSilent, pasta_aimbot_hammer_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer silent")
MACRO_CONFIG_INT(PastaAimbotHammerIgnoreFriends, pasta_aimbot_hammer_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hammer ignore friends")

MACRO_CONFIG_INT(PastaAimbotPistol, pasta_aimbot_pistol, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pistol aimbot")
MACRO_CONFIG_INT(PastaAimbotPistolFov, pasta_aimbot_pistol_fov, 60, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pistol aimbot fov")
MACRO_CONFIG_INT(PastaAimbotPistolTargetPriority, pasta_aimbot_pistol_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pistol target priority")
MACRO_CONFIG_INT(PastaAimbotPistolSilent, pasta_aimbot_pistol_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pistol silent")
MACRO_CONFIG_INT(PastaAimbotPistolIgnoreFriends, pasta_aimbot_pistol_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pistol ignore friends")

MACRO_CONFIG_INT(PastaAimbotShotgun, pasta_aimbot_shotgun, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun aimbot")
MACRO_CONFIG_INT(PastaAimbotShotgunFov, pasta_aimbot_shotgun_fov, 100, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun aimbot fov")
MACRO_CONFIG_INT(PastaAimbotShotgunTargetPriority, pasta_aimbot_shotgun_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun target priority")
MACRO_CONFIG_INT(PastaAimbotShotgunSilent, pasta_aimbot_shotgun_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun silent")
MACRO_CONFIG_INT(PastaAimbotShotgunIgnoreFriends, pasta_aimbot_shotgun_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun ignore friends")

MACRO_CONFIG_INT(PastaAimbotGrenade, pasta_aimbot_grenade, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade aimbot")
MACRO_CONFIG_INT(PastaAimbotGrenadeFov, pasta_aimbot_grenade_fov, 120, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade aimbot fov")
MACRO_CONFIG_INT(PastaAimbotGrenadeTargetPriority, pasta_aimbot_grenade_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade target priority")
MACRO_CONFIG_INT(PastaAimbotGrenadeSilent, pasta_aimbot_grenade_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade silent")
MACRO_CONFIG_INT(PastaAimbotGrenadeIgnoreFriends, pasta_aimbot_grenade_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Grenade ignore friends")

MACRO_CONFIG_INT(PastaAimbotLaser, pasta_aimbot_laser, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser aimbot")
MACRO_CONFIG_INT(PastaAimbotLaserFov, pasta_aimbot_laser_fov, 40, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser aimbot fov")
MACRO_CONFIG_INT(PastaAimbotLaserTargetPriority, pasta_aimbot_laser_target_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser target priority")
MACRO_CONFIG_INT(PastaAimbotLaserSilent, pasta_aimbot_laser_silent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser silent")
MACRO_CONFIG_INT(PastaAimbotLaserIgnoreFriends, pasta_aimbot_laser_ignore_friends, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser ignore friends")

// Misc
MACRO_CONFIG_INT(PastaMoonwalk, pasta_moonwalk, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Moonwalk")
MACRO_CONFIG_INT(PastaAutoFire, pasta_autofire, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto fire")
MACRO_CONFIG_INT(PastaAutoRehook, pasta_autorehook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto rehook")
MACRO_CONFIG_INT(PastaAutoJumpSave, pasta_autojumpsave, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto jump save")
MACRO_CONFIG_INT(PastaAutoJumpSaveMode, pasta_autojumpsave_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto jump save mode")
MACRO_CONFIG_INT(PastaQuickStop, pasta_quickstop, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Quick stop")
MACRO_CONFIG_INT(PastaQuickStopGrounded, pasta_quickstop_grounded, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Quick stop grounded")
MACRO_CONFIG_INT(PastaDummyFly, pasta_dummyfly, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Dummy fly")
MACRO_CONFIG_INT(PastaJetRide, pasta_jetride, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Jet ride")
MACRO_CONFIG_INT(PastaAutoAled, pasta_autoaled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto aled")

MACRO_CONFIG_INT(PastaRandomTimeoutSeed, pasta_randomtimeoutseed, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Random timeout seed")
MACRO_CONFIG_INT(PastaSpoofVersion, pasta_spoofversion, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Version spoofer")
MACRO_CONFIG_INT(PastaSpoofVersionAdvancedSettings, pasta_spoofversion_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show advanced version spoofer settings")
MACRO_CONFIG_INT(PastaSpoofVersionNr, pasta_spoofversion_nr, 18010, 0, 99999, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Spoofed version number")

MACRO_CONFIG_INT(PastaModDetector, pasta_moddetector, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable mod detector")
MACRO_CONFIG_INT(PastaModDetectorNames, pasta_moddetectornames, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect by names")
MACRO_CONFIG_INT(PastaModDetectorWarn, pasta_moddetector_warn, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect suspicious players")
MACRO_CONFIG_INT(PastaModDetectorLeave, pasta_moddetector_leave, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Leave on mod detection")
MACRO_CONFIG_INT(PastaModDetectorWarnLeave, pasta_moddetector_warnleave, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Leave on warn detected")

MACRO_CONFIG_INT(PastaAutoEdge, pasta_autoedge, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge")
MACRO_CONFIG_INT(PastaAutoEdgeDetectFreeze, pasta_autoedge_detect_freeze, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect freeze")
MACRO_CONFIG_INT(PastaAutoEdgeDetectDeath, pasta_autoedge_detect_death, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect death")
MACRO_CONFIG_INT(PastaAutoEdgeDetectTele, pasta_autoedge_detect_tele, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect tele")
MACRO_CONFIG_INT(PastaAutoEdgeShowFound, pasta_autoedge_show_found, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show found edges")
MACRO_CONFIG_INT(PastaAutoEdgeShowLocked, pasta_autoedge_show_locked, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show locked edge")
MACRO_CONFIG_INT(PastaAutoEdgeAdvancedSettings, pasta_autoedge_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show advanced auto edge settings")
MACRO_CONFIG_INT(PastaAutoEdgeDetectionRange, pasta_autoedge_detection_range, 10, 1, 40, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge detection range")
MACRO_CONFIG_INT(PastaAutoEdgePopulationSize, pasta_autoedge_population_size, 128, 10, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge population size")
MACRO_CONFIG_INT(PastaAutoEdgeExplorationDepth, pasta_autoedge_exploration_depth, 10, 1, 40, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge exploration depth")
MACRO_CONFIG_INT(PastaAutoEdgeTopK, pasta_autoedge_top_k, 16, 1, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge top k")
MACRO_CONFIG_INT(PastaAutoEdgeSequenceLength, pasta_autoedge_sequence_length, 2, 1, 32, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto edge sequence length")

MACRO_CONFIG_INT(PastaAutoShotgun, pasta_autoshotgun, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun")
MACRO_CONFIG_INT(PastaAutoShotgunAdvancedSettings, pasta_autoshotgun_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show advanced auto shotgun settings")
MACRO_CONFIG_INT(PastaAutoShotgunMostBounces, pasta_autoshotgunmostbounces, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun bounce preference")
MACRO_CONFIG_INT(PastaAutoShotgunHighestVel, pasta_autoshotgunhighestvel, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun speed preference")
MACRO_CONFIG_INT(PastaAutoShotgunSilent, pasta_autoshotgunsilent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun silent")
MACRO_CONFIG_INT(PastaAutoShotgunPoints, pasta_autoshotgunpoints, 12, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun points")
MACRO_CONFIG_INT(PastaAutoShotgunTicks, pasta_autoshotgunticks, 8, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun ticks")
MACRO_CONFIG_INT(PastaAutoShotgunFov, pasta_autoshotgunfov, 180, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto shotgun fov")

MACRO_CONFIG_INT(PastaUnfreezeBot, pasta_unfreezebot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze")
MACRO_CONFIG_INT(PastaUnfreezeBotEsp, pasta_unfreezebotesp, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze esp")
MACRO_CONFIG_INT(PastaUnfreezeBotAdvancedSettings, pasta_unfreezebot_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show advanced auto unfreeze settings")
MACRO_CONFIG_INT(PastaUnfreezeBotMostBounces, pasta_unfreezebotmostbounces, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze bounce preference")
MACRO_CONFIG_INT(PastaUnfreezeBotSilent, pasta_unfreezebotsilent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze silent")
MACRO_CONFIG_INT(PastaUnfreezeBotPoints, pasta_unfreezebotpoints, 12, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze points")
MACRO_CONFIG_INT(PastaUnfreezeBotCurDirTicks, pasta_unfreezebotcurdirticks, 4, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze current direction ticks")
MACRO_CONFIG_INT(PastaUnfreezeBotTicks, pasta_unfreezebotticks, 10, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze ticks")
MACRO_CONFIG_INT(PastaUnfreezeBotFov, pasta_unfreezebotfov, 180, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto unfreeze fov")

MACRO_CONFIG_INT(PastaPredictionBenchmark, pasta_prediction_benchmark, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction benchmark")
MACRO_CONFIG_INT(PastaPredictionBenchmarkRuns, pasta_prediction_benchmark_runs, 1, 1, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction benchmark runs")
MACRO_CONFIG_INT(PastaPredictionBenchmarkThreads, pasta_prediction_benchmark_threads, 1, 1, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction benchmark threads")

MACRO_CONFIG_INT(PastaChangeNameOnFinish, pasta_change_name_on_finish, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Change name on finish")
MACRO_CONFIG_INT(PastaChangeNameOnFinishRandom, pasta_change_name_on_finish_random, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use random finish name")
MACRO_CONFIG_STR(PastaChangeNameOnFinishName, pasta_change_name_on_finish_name, 24, "pasta tee", CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_INSENSITIVE, "Finish name")
MACRO_CONFIG_INT(PastaAutoTeam, pasta_auto_team, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto team")
MACRO_CONFIG_INT(PastaAutoTeamPreferred, pasta_auto_team_preferred, 1, 1, 63, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Preferred team")
MACRO_CONFIG_INT(PastaAntiAfk, pasta_anti_afk, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Anti afk")
MACRO_CONFIG_INT(PastaAntiAfkSeconds, pasta_anti_afk_seconds, 20, 1, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Anti afk seconds")
MACRO_CONFIG_INT(PastaKillOnFreeze, pasta_killonfreeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Kill on freeze")
MACRO_CONFIG_INT(PastaFastInput, pasta_fast_input, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fast input")
MACRO_CONFIG_INT(PastaFastInputOthers, pasta_fast_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fast input others")
MACRO_CONFIG_INT(PastaIgnoreReplayWarnings, pasta_ignore_replay_warnings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ignore replay warnings")
MACRO_CONFIG_INT(PastaHideBubble, pasta_hidebubble, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide chat bubble")
MACRO_CONFIG_INT(PastaSendAds, pasta_sendads, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Send ads")

MACRO_CONFIG_INT(PastaEmoteSpam, pasta_emotespam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Emote spam")
MACRO_CONFIG_INT(PastaKillsay, pasta_killsay, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Killsay")
MACRO_CONFIG_INT(PastaFancyChatFont, pasta_fancychatfont, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fancy chat font")
MACRO_CONFIG_INT(PastaMassMentionSpam, pasta_massmentionspam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mass mention spam")
MACRO_CONFIG_INT(PastaChatRepeater, pasta_chatrepeater, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat repeater")
MACRO_CONFIG_INT(PastaChatRepeaterLength, pasta_chatrepeater_length, 12, 1, 256, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat repeater min length")

MACRO_CONFIG_INT(PastaIdStealer, pasta_idstealer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer")
MACRO_CONFIG_INT(PastaIdStealerClosest, pasta_idstealer_closest, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer closest player")
MACRO_CONFIG_INT(PastaIdStealerName, pasta_idstealer_name, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer name")
MACRO_CONFIG_INT(PastaIdStealerClan, pasta_idstealer_clan, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer clan")
MACRO_CONFIG_INT(PastaIdStealerSkin, pasta_idstealer_skin, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer skin")
MACRO_CONFIG_INT(PastaIdStealerFlag, pasta_idstealer_flag, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer flag")
MACRO_CONFIG_INT(PastaIdStealerEmote, pasta_idstealer_emote, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer emote")
MACRO_CONFIG_INT(PastaIdStealerSpeed, pasta_idstealer_speed, 3, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Id stealer speed")

MACRO_CONFIG_INT(PastaGhostMove, pasta_ghostmove, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ghost move")
MACRO_CONFIG_INT(PastaGhostMoveDirection, pasta_ghostmovedirection, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ghost move direction")
MACRO_CONFIG_INT(PastaGhostMoveJump, pasta_ghostmovejump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ghost move jump")
MACRO_CONFIG_INT(PastaGhostMoveHook, pasta_ghostmovehook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ghost move hook")
MACRO_CONFIG_INT(PastaGhostMoveHookClosest, pasta_ghostmovehookclosest, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ghost move hook closest")

MACRO_CONFIG_INT(PastaAutoVote, pasta_autovote, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote")
MACRO_CONFIG_INT(PastaAutoVoteF4, pasta_autovotef4, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote choice")
MACRO_CONFIG_INT(PastaAutoVoteKick, pasta_autovotekick, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote kick")
MACRO_CONFIG_INT(PastaAutoVoteKickMode, pasta_autovotekick_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote kick mode")
MACRO_CONFIG_INT(PastaAutoVoteKickTarget, pasta_autovotekick_target, 0, 0, 63, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote kick target")
MACRO_CONFIG_STR(PastaAutoVoteKickReason, pasta_autovotekick_reason, 64, "pasta detected", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto vote kick reason")

MACRO_CONFIG_INT(PastaFakeAim, pasta_fake_aim, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fake aim")
MACRO_CONFIG_INT(PastaFakeAimSendAlways, pasta_fake_aim_send_always, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fake aim send always")
MACRO_CONFIG_INT(PastaFakeAimVisible, pasta_fake_aim_visible, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fake aim visible")
MACRO_CONFIG_INT(PastaFakeAimMode, pasta_fake_aim_mode, 0, 0, 5, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fake aim mode")
MACRO_CONFIG_INT(PastaFakeAimSpeed, pasta_fake_aim_speed, 5, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fake aim speed")

// Visuals & HUD
MACRO_CONFIG_INT(PastaFeaturesHud, pasta_featureshud, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud")
MACRO_CONFIG_INT(PastaFeaturesHudOpacity, pasta_featureshudopacity, 10, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud opacity")
MACRO_CONFIG_INT(PastaFeaturesHudFontSize, pasta_featureshudfontsize, 6, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud font size")
MACRO_CONFIG_INT(PastaFeaturesHudSegmented, pasta_featureshudsegmented, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud segmented")
MACRO_CONFIG_INT(PastaFeaturesHudGradientSpeed, pasta_featureshudgradientspeed, 1, 0, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud gradient speed")
MACRO_CONFIG_COL(PastaFeaturesHudGradientStartCol, pasta_featureshudgradientstartcol, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud start color")
MACRO_CONFIG_COL(PastaFeaturesHudGradientEndCol, pasta_featureshudgradientendcol, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud end color")
MACRO_CONFIG_INT(PastaFeaturesHudGradientRainbow, pasta_featureshudgradientrainbow, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Features hud rainbow")
MACRO_CONFIG_INT(PastaTasHud, pasta_tashud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas hud")
MACRO_CONFIG_INT(PastaTasInit, pasta_tas_init, 0, 0, 1, CFGFLAG_CLIENT, "Tas world initialized")
MACRO_CONFIG_INT(PastaNotifications, pasta_notifications, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Notifications")

MACRO_CONFIG_INT(PastaWatermark, pasta_watermark, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark")
MACRO_CONFIG_INT(PastaWatermarkSegmented, pasta_watermarksegmented, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark segmented")
MACRO_CONFIG_INT(PastaWatermarkGradientSpeed, pasta_watermarkgradientspeed, 1, 0, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark gradient speed")
MACRO_CONFIG_COL(PastaWatermarkGradientStartCol, pasta_watermarkgradientstartcol, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark start color")
MACRO_CONFIG_COL(PastaWatermarkGradientEndCol, pasta_watermarkgradientendcol, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark end color")
MACRO_CONFIG_INT(PastaWatermarkGradientRainbow, pasta_watermarkgradientrainbow, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Watermark rainbow")

MACRO_CONFIG_INT(PastaNowPlayingHud, pasta_nowplayinghud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing hud")
MACRO_CONFIG_INT(PastaNowPlayingSegmented, pasta_nowplayingsegmented, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing segmented")
MACRO_CONFIG_INT(PastaNowPlayingGradientSpeed, pasta_nowplayinggradientspeed, 1, 0, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing gradient speed")
MACRO_CONFIG_COL(PastaNowPlayingGradientStartCol, pasta_nowplayinggradientstartcol, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing start color")
MACRO_CONFIG_COL(PastaNowPlayingGradientEndCol, pasta_nowplayinggradientendcol, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing end color")
MACRO_CONFIG_INT(PastaNowPlayingGradientRainbow, pasta_nowplayinggradientrainbow, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Now playing rainbow")

MACRO_CONFIG_INT(PastaCustomColorTee, pasta_customcolortee, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom color tee")
MACRO_CONFIG_INT(PastaCustomColorHook, pasta_customcolorhook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom color hook")
MACRO_CONFIG_INT(PastaCustomColorWeapon, pasta_customcolorweapon, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom color weapon")
MACRO_CONFIG_INT(PastaCustomColorTeeRainbow, pasta_customcolorteerainbow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rainbow tee")
MACRO_CONFIG_INT(PastaCustomColorHookRainbow, pasta_customcolorhookrainbow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rainbow hook")
MACRO_CONFIG_INT(PastaCustomColorRainbowSpeed, pasta_customcolorrainbowspeed, 100, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rainbow speed")

MACRO_CONFIG_INT(PastaCustomFrozenColor, pasta_custom_frozen_color, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom frozen color")
MACRO_CONFIG_COL(PastaCustomFrozenColorValue, pasta_custom_frozen_color_value, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom frozen color value")

MACRO_CONFIG_INT(PastaTrail, pasta_trail, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail")
MACRO_CONFIG_INT(PastaTrailType, pasta_trail_type, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail type")
MACRO_CONFIG_COL(PastaTrailColor, pasta_trail_color, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail color")
MACRO_CONFIG_INT(PastaTrailColorRainbow, pasta_trail_color_rainbow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail rainbow")
MACRO_CONFIG_INT(PastaTrailLowTaper, pasta_trail_low_taper, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail low taper")
MACRO_CONFIG_INT(PastaTrailFade, pasta_trail_fade, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail fade")
MACRO_CONFIG_INT(PastaTrailColorMode, pasta_trail_color_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail color mode")
MACRO_CONFIG_INT(PastaTrailWidth, pasta_trail_width, 15, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail width")
MACRO_CONFIG_INT(PastaTrailLength, pasta_trail_length, 25, 1, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail length")
MACRO_CONFIG_INT(PastaTrailAlpha, pasta_trail_alpha, 80, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trail alpha")

MACRO_CONFIG_INT(PastaRainbowMenu, pasta_rainbowmenu, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rainbow menu")
MACRO_CONFIG_INT(PastaCustomTheme, pasta_customtheme, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom theme")
MACRO_CONFIG_COL(PastaCustomAccentColor, pasta_custom_accent_color, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom accent color")
MACRO_CONFIG_COL(PastaCustomBgColor, pasta_custom_bg_color, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom background color")

MACRO_CONFIG_INT(PastaTrajectoryEsp, pasta_trajectoryesp, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory esp")
MACRO_CONFIG_INT(PastaTrajectoryEspSelfOnly, pasta_trajectoryespselfonly, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory esp self only")
MACRO_CONFIG_INT(PastaTrajectoryEspTicks, pasta_trajectoryespticks, 40, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory esp ticks")
MACRO_CONFIG_INT(PastaTrajectoryEspThickness, pasta_trajectoryesp_thickness, 2, 1, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory thickness")
MACRO_CONFIG_INT(PastaTrajectoryEspMode, pasta_trajectoryesp_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory path mode")
MACRO_CONFIG_COL(PastaTrajectoryEspColorLocal, pasta_trajectoryesp_color_local, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory local color")
MACRO_CONFIG_COL(PastaTrajectoryEspColorFrozen, pasta_trajectoryesp_color_frozen, 65535, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory frozen color")
MACRO_CONFIG_COL(PastaTrajectoryEspColorOthers, pasta_trajectoryesp_color_others, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trajectory others color")

MACRO_CONFIG_INT(PastaSmoothCam, pasta_smoothcam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smooth cam")
MACRO_CONFIG_INT(PastaSmoothCamSmoothness, pasta_smoothcam_smoothness, 50, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smooth cam smoothness")
MACRO_CONFIG_INT(PastaSuperDyncam, pasta_superdyncam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Super dyncam")

MACRO_CONFIG_INT(PastaTileOutlines, pasta_tile_outlines, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tile outlines")
MACRO_CONFIG_INT(PastaTileOutlinesFreeze, pasta_tile_outlines_freeze, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze outlines")
MACRO_CONFIG_INT(PastaTileOutlinesKill, pasta_tile_outlines_kill, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Kill outlines")
MACRO_CONFIG_INT(PastaTileOutlinesUnfreeze, pasta_tile_outlines_unfreeze, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Unfreeze outlines")
MACRO_CONFIG_INT(PastaTileOutlinesTele, pasta_tile_outlines_tele, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tele outlines")
MACRO_CONFIG_INT(PastaTileOutlinesSolid, pasta_tile_outlines_solid, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Wall outlines")
MACRO_CONFIG_INT(PastaTileOutlinesWidth, pasta_tile_outlines_width, 2, 1, 16, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Outline width")
MACRO_CONFIG_INT(PastaTileOutlinesAlpha, pasta_tile_outlines_alpha, 75, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Outline alpha")
MACRO_CONFIG_COL(PastaTileOutlineColorFreeze, pasta_tile_outline_color_freeze, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze outline color")
MACRO_CONFIG_COL(PastaTileOutlineColorKill, pasta_tile_outline_color_kill, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Kill outline color")
MACRO_CONFIG_COL(PastaTileOutlineColorUnfreeze, pasta_tile_outline_color_unfreeze, 65535, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Unfreeze outline color")
MACRO_CONFIG_COL(PastaTileOutlineColorTele, pasta_tile_outline_color_tele, 16384, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tele outline color")
MACRO_CONFIG_COL(PastaTileOutlineColorSolid, pasta_tile_outline_color_solid, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Wall outline color")

MACRO_CONFIG_INT(PastaPlayerIndicator, pasta_player_indicator, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player indicator")
MACRO_CONFIG_INT(PastaIndicatorSize, pasta_indicator_size, 4, 1, 16, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator size")
MACRO_CONFIG_INT(PastaIndicatorOffset, pasta_indicator_offset, 42, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator offset")
MACRO_CONFIG_INT(PastaIndicatorOpacity, pasta_indicator_opacity, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator opacity")
MACRO_CONFIG_INT(PastaIndicatorTeamOnly, pasta_indicator_team_only, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator team only")
MACRO_CONFIG_INT(PastaIndicatorTees, pasta_indicator_tees, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator tees")
MACRO_CONFIG_INT(PastaIndicatorHideVisible, pasta_indicator_hide_visible, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicator hide visible")

MACRO_CONFIG_INT(PastaShowFrozenHud, pasta_frozen_tees_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee hud")
MACRO_CONFIG_INT(PastaShowFrozenHudSkins, pasta_frozen_tees_hud_skins, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee hud skins")
MACRO_CONFIG_INT(PastaShowFrozenHudOnlyInTeam, pasta_frozen_tees_only_inteam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee hud only in team")
MACRO_CONFIG_INT(PastaShowFrozenHudMaxRows, pasta_frozen_tees_max_rows, 1, 1, 6, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee hud max rows")
MACRO_CONFIG_INT(PastaShowFrozenHudSize, pasta_frozen_tees_size, 15, 8, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee hud size")
MACRO_CONFIG_INT(PastaFrozenTeesText, pasta_frozen_tees_text, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen tee text mode")

MACRO_CONFIG_INT(PastaShowWhenLast, pasta_last_notify, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show when last")
MACRO_CONFIG_STR(PastaShowWhenLastText, pasta_last_notify_text, 64, "Last!", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show when last text")
MACRO_CONFIG_COL(PastaShowWhenLastColor, pasta_last_notify_color, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show when last color")
MACRO_CONFIG_INT(PastaCursorInSpec, pasta_cursor_in_spec, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cursor in spec")

MACRO_CONFIG_INT(PastaAimLines, pasta_drawaimlines, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines")
MACRO_CONFIG_INT(PastaAimLinesSelfOnly, pasta_drawaimlines_selfonly, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines self only")
MACRO_CONFIG_INT(PastaAimLinesGun, pasta_drawaimlines_gun, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines gun")
MACRO_CONFIG_INT(PastaAimLinesShotgun, pasta_drawaimlines_shotgun, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines shotgun")
MACRO_CONFIG_INT(PastaAimLinesGrenade, pasta_drawaimlines_grenade, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines grenade")
MACRO_CONFIG_INT(PastaAimLinesLaser, pasta_drawaimlines_laser, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines laser")
MACRO_CONFIG_INT(PastaAimLinesAlpha, pasta_drawaimlines_alpha, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim lines alpha")

MACRO_CONFIG_INT(PastaBulletLines, pasta_drawbulletlines, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines")
MACRO_CONFIG_INT(PastaBulletLinesSelfOnly, pasta_drawbulletlines_selfonly, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines self only")
MACRO_CONFIG_INT(PastaBulletLinesGun, pasta_drawbulletlines_gun, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines gun")
MACRO_CONFIG_INT(PastaBulletLinesShotgun, pasta_drawbulletlines_shotgun, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines shotgun")
MACRO_CONFIG_INT(PastaBulletLinesGrenade, pasta_drawbulletlines_grenade, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines grenade")
MACRO_CONFIG_INT(PastaBulletLinesAlpha, pasta_drawbulletlines_alpha, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bullet lines alpha")

// Avoid
MACRO_CONFIG_INT(PastaAvoidfreeze, pasta_avoidfreeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Avoid freeze")

MACRO_CONFIG_INT(PastaAvoidLegitPlayerPrediction, pasta_avoid_legit_player_prediction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit player prediction")
MACRO_CONFIG_INT(PastaAvoidLegitAfkProtection, pasta_avoid_legit_afk_protection, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit afk protection")
MACRO_CONFIG_INT(PastaAvoidLegitAfkTime, pasta_avoid_legit_afk_time, 5, 1, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit afk time")
MACRO_CONFIG_INT(PastaAvoidLegitHook, pasta_avoid_legit_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit hook")
MACRO_CONFIG_INT(PastaAvoidLegitDirection, pasta_avoid_legit_direction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit direction")
MACRO_CONFIG_INT(PastaAvoidLegitCheckTicks, pasta_avoid_legit_check_ticks, 6, 1, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit check ticks")
MACRO_CONFIG_INT(PastaAvoidLegitQuality, pasta_avoid_legit_quality, 16, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit quality")
MACRO_CONFIG_INT(PastaAvoidLegitRandomness, pasta_avoid_legit_randomness, 14, 0, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit randomness")
MACRO_CONFIG_INT(PastaAvoidLegitDirectionPriority, pasta_avoid_legit_direction_priority, 346, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit direction priority")
MACRO_CONFIG_INT(PastaAvoidLegitHookPriority, pasta_avoid_legit_hook_priority, 1000, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit hook priority")
MACRO_CONFIG_INT(PastaAvoidLegitLifePriority, pasta_avoid_legit_life_priority, 13, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit life priority")
MACRO_CONFIG_INT(PastaAvoidLegitTeles, pasta_avoid_legit_teles, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit teles")
MACRO_CONFIG_INT(PastaAvoidLegitDeath, pasta_avoid_legit_death, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit death")
MACRO_CONFIG_INT(PastaAvoidLegitUnfreeze, pasta_avoid_legit_unfreeze, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit unfreeze")
MACRO_CONFIG_INT(PastaAvoidLegitUnfreezeTicks, pasta_avoid_legit_unfreeze_ticks, 5, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legit unfreeze ticks")

MACRO_CONFIG_INT(PastaAvoidBlatantPlayerPrediction, pasta_avoid_blatant_player_prediction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant player prediction")
MACRO_CONFIG_INT(PastaAvoidBlatantNsif, pasta_avoid_blatant_nsif, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant nsif")
MACRO_CONFIG_INT(PastaAvoidBlatantAfkProtection, pasta_avoid_blatant_afk_protection, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant afk protection")
MACRO_CONFIG_INT(PastaAvoidBlatantAfkTime, pasta_avoid_blatant_afk_time, 5, 1, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant afk time")
MACRO_CONFIG_INT(PastaAvoidBlatantHook, pasta_avoid_blatant_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant hook")
MACRO_CONFIG_INT(PastaAvoidBlatantDirection, pasta_avoid_blatant_direction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant direction")
MACRO_CONFIG_INT(PastaAvoidBlatantMinTicks, pasta_avoid_blatant_min_ticks, 4, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant minimum predict ticks")
MACRO_CONFIG_INT(PastaAvoidBlatantMaxTicks, pasta_avoid_blatant_max_ticks, 25, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant maximum predict ticks")
MACRO_CONFIG_INT(PastaAvoidBlatantVelocityTickFactor, pasta_avoid_blatant_velocity_tick_factor, 10, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant velocity tick factor")
MACRO_CONFIG_INT(PastaAvoidBlatantCanSetDir, pasta_avoid_blatant_can_set_dir, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant can set direction")
MACRO_CONFIG_INT(PastaAvoidBlatantOnlyHorizontally, pasta_avoid_blatant_only_horizontally, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant only horizontally")
MACRO_CONFIG_INT(PastaAvoidBlatantCheckTicks, pasta_avoid_blatant_check_ticks, 26, 1, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant check ticks")
MACRO_CONFIG_INT(PastaAvoidBlatantKickInTicks, pasta_avoid_blatant_kick_in_ticks, 26, 1, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant kick in ticks")
MACRO_CONFIG_INT(PastaAvoidBlatantFreezeReset, pasta_avoid_blatant_freeze_reset, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant freeze reset")
MACRO_CONFIG_INT(PastaAvoidBlatantFreezeResetWait, pasta_avoid_blatant_freeze_reset_wait, 0, 0, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant freeze reset wait")
MACRO_CONFIG_INT(PastaAvoidBlatantFreezeResetFriendDist, pasta_avoid_blatant_freeze_reset_friend_dist, 0, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant freeze reset friend radius")
MACRO_CONFIG_INT(PastaAvoidBlatantTrackPoint, pasta_avoid_blatant_track_point, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant track point")
MACRO_CONFIG_INT(PastaAvoidBlatantSafeAimTracking, pasta_avoid_blatant_safe_aim_tracking, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant safe aim tracking")
MACRO_CONFIG_INT(PastaAvoidTileAutoDrag, pasta_avoid_tile_auto_drag, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant auto drag key state")
MACRO_CONFIG_INT(PastaAvoidTileTrackPoints, pasta_avoid_tile_track_points, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant track point key state")
MACRO_CONFIG_INT(PastaAvoidBlatantTeles, pasta_avoid_blatant_teles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant teles")
MACRO_CONFIG_INT(PastaAvoidBlatantDeath, pasta_avoid_blatant_death, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant death")
MACRO_CONFIG_INT(PastaAvoidBlatantUnfreeze, pasta_avoid_blatant_unfreeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant unfreeze")
MACRO_CONFIG_INT(PastaAvoidBlatantUnfreezeTicks, pasta_avoid_blatant_unfreeze_ticks, 5, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant unfreeze ticks")
MACRO_CONFIG_INT(PastaAvoidBlatantAimbot, pasta_avoid_blatant_aimbot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant aimbot")
MACRO_CONFIG_INT(PastaAvoidBlatantAimbotSegments, pasta_avoid_blatant_aimbot_segments, 64, 1, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant aimbot segments")
MACRO_CONFIG_INT(PastaAvoidBlatantAimbotFov, pasta_avoid_blatant_aimbot_fov, 180, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant aimbot fov")
MACRO_CONFIG_INT(PastaAvoidBlatantAimbotMode, pasta_avoid_blatant_aimbot_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant aimbot mode")
MACRO_CONFIG_INT(PastaAvoidBlatantVisualTrackPoint, pasta_avoid_blatant_visual_track_point, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant visual track point")
MACRO_CONFIG_INT(PastaAvoidBlatantVisualAimbot, pasta_avoid_blatant_visual_aimbot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blatant visual aimbot")

MACRO_CONFIG_INT(PastaAvoidFentPlayerPrediction, pasta_avoid_fent_player_prediction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent player prediction")
MACRO_CONFIG_INT(PastaAvoidFentUnfreeze, pasta_avoid_fent_unfreeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent unfreeze")
MACRO_CONFIG_INT(PastaAvoidFentUnfreezeRadius, pasta_avoid_fent_unfreeze_radius, 4, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent unfreeze radius")
MACRO_CONFIG_INT(PastaAvoidFentAdvancedSettings, pasta_avoid_fent_advanced_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent advanced settings")
MACRO_CONFIG_INT(PastaAvoidFentTicks, pasta_avoid_fent_ticks, 1000, 10, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent ticks")
MACRO_CONFIG_INT(PastaAvoidFentTweakerInputs, pasta_avoid_fent_tweaker_inputs, 500, 1, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent tweaker inputs")
MACRO_CONFIG_INT(PastaAvoidFentTweakerTicks, pasta_avoid_fent_tweaker_ticks, 8, 1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent tweaker ticks")
MACRO_CONFIG_INT(PastaAvoidFentTweakerDosage, pasta_avoid_fent_tweaker_dosage, 100, 1, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent tweaker dosage")
MACRO_CONFIG_INT(PastaAvoidFentQualitySetting, pasta_avoid_fent_quality_setting, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent quality")
MACRO_CONFIG_INT(PastaAvoidFentRenderPath, pasta_avoid_fent_render_path, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent render path")
MACRO_CONFIG_INT(PastaAvoidFentRenderPathfinding, pasta_avoid_fent_render_pathfinding, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent render pathfinding")
MACRO_CONFIG_INT(PastaAvoidFentSpectateScan, pasta_avoid_fent_spectate_scan, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent spectate scan")
MACRO_CONFIG_INT(PastaAvoidFentEnableEditor, pasta_avoid_fent_enable_editor, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent enable editor")
MACRO_CONFIG_INT(PastaAvoidFentTileType, pasta_avoid_fent_tile_type, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent tile type")
MACRO_CONFIG_INT(PastaAvoidFentAutoTunnelWidth, pasta_avoid_fent_auto_tunnel_width, 2, 1, 16, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fent auto tunnel width")

MACRO_CONFIG_INT(PastaAvoidPilotPlayerPrediction, pasta_avoid_pilot_player_prediction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot player prediction")
MACRO_CONFIG_INT(PastaAvoidPilotMode, pasta_avoid_pilot_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot mode")
MACRO_CONFIG_INT(PastaAvoidPilotPopulationSize, pasta_avoid_pilot_population_size, 399, 1, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot population")
MACRO_CONFIG_INT(PastaAvoidPilotExplorationDepth, pasta_avoid_pilot_exploration_depth, 13, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot exploration depth")
MACRO_CONFIG_INT(PastaAvoidPilotTopKCandidates, pasta_avoid_pilot_top_k_candidates, 22, 1, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot top k")
MACRO_CONFIG_INT(PastaAvoidPilotSequenceLength, pasta_avoid_pilot_sequence_length, 1, 1, 32, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot sequence length")
MACRO_CONFIG_INT(PastaAvoidPilotRenderPath, pasta_avoid_pilot_render_path, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot render path")
MACRO_CONFIG_INT(PastaAvoidPilotRenderPathfinding, pasta_avoid_pilot_render_pathfinding, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot render pathfinding")
MACRO_CONFIG_INT(PastaAvoidPilotEnableEditor, pasta_avoid_pilot_enable_editor, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot enable editor")
MACRO_CONFIG_INT(PastaAvoidPilotTileType, pasta_avoid_pilot_tile_type, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot tile type")
MACRO_CONFIG_INT(PastaAvoidPilotAutoTunnelWidth, pasta_avoid_pilot_auto_tunnel_width, 2, 1, 16, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pilot auto tunnel width")

// TAS
MACRO_CONFIG_INT(PastaTasTps, pasta_tastps, 50, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas ticks per second")
MACRO_CONFIG_INT(PastaTasPause, pasta_taspause, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas pause")
MACRO_CONFIG_INT(PastaLoadReplay, pasta_loadreplay, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Load replay")
MACRO_CONFIG_INT(PastaRecordReplay, pasta_recordreplay, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Record replay")
MACRO_CONFIG_INT(PastaTasRespawn, pasta_tasrespawn, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas respawn")
MACRO_CONFIG_INT(PastaTasRewind, pasta_tasrewind, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas rewind")
MACRO_CONFIG_INT(PastaTasForward, pasta_tasforward, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas forward")
MACRO_CONFIG_INT(PastaTasUseSound, pasta_tasusesound, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas use sound")
MACRO_CONFIG_INT(PastaTasShowEffects, pasta_tasshoweffects, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas show effects")
MACRO_CONFIG_INT(PastaTasShowAim, pasta_tasshowaim, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas show aim")
MACRO_CONFIG_INT(PastaTasPlayerPrediction, pasta_tasplayerprediction, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas player prediction")
MACRO_CONFIG_INT(PastaTasAutoReplay, pasta_tasautoreplay, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto replay")
MACRO_CONFIG_INT(PastaTasAutoReplayFreeze, pasta_tasautoreplayfreeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto replay on freeze")
MACRO_CONFIG_INT(PastaTasAutoReplayKill, pasta_tasautoreplaykill, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto replay kill")
MACRO_CONFIG_INT(PastaAutoSaveReplay, pasta_autosavereplay, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto save replay")
MACRO_CONFIG_INT(PastaAutoSaveReplayInterval, pasta_autosavereplayinterval, 30, 1, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto save replay interval")
MACRO_CONFIG_STR(PastaTasReplayName, pasta_tas_replay_name, 64, "my_tas", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas replay selection")
MACRO_CONFIG_INT(PastaTasReplayVaultAutoSync, pasta_tasreplayvaultautosync, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Replay vault auto sync")
MACRO_CONFIG_INT(PastaTasTickControlTicks, pasta_tastickcontrolticks, 1, 1, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas tick control ticks")
MACRO_CONFIG_INT(PastaTasAutoRewind, pasta_tasautorewind, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto rewind")
MACRO_CONFIG_INT(PastaTasAutoForward, pasta_tasautoforward, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto forward")
MACRO_CONFIG_INT(PastaTickControlPause, pasta_tickcontrolpause, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas auto pause")
MACRO_CONFIG_INT(PastaTickControlStep, pasta_tickcontrolstep, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas step")
MACRO_CONFIG_INT(PastaTasFakeAimMode, pasta_tas_fake_aim_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas fake aim mode")
MACRO_CONFIG_INT(PastaTasFakeAim, pasta_tas_fake_aim, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Tas fake aim trigger")
MACRO_CONFIG_INT(PastaTasDrawStartEndPos, pasta_tasdrawstartendpos, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw start end pos")
MACRO_CONFIG_INT(PastaTasDrawPath, pasta_tasdrawpath, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw replay path")
MACRO_CONFIG_INT(PastaTasDrawPathSegmented, pasta_tasdrawpathsegmented, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw segmented replay path")
MACRO_CONFIG_INT(PastaTasDrawPathMode, pasta_tasdrawpathmode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw replay path mode")
MACRO_CONFIG_COL(PastaTasDrawPathColor, pasta_tasdrawpathcolor, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Replay path color")
MACRO_CONFIG_INT(PastaTasDrawPredictionPath, pasta_tasdrawpredictionpath, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw prediction path")
MACRO_CONFIG_INT(PastaTasDrawPredictionPathMode, pasta_tasdrawpredictionpathmode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw prediction path mode")
MACRO_CONFIG_COL(PastaTasDrawPredictionPathColor, pasta_tasdrawpredictionpathcolor, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction path local color")
MACRO_CONFIG_COL(PastaTasDrawPredictionPathColorFrozen, pasta_tasdrawpredictionpathcolorfrozen, 65535, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction path frozen color")
MACRO_CONFIG_COL(PastaTasDrawPredictionPathColorOthers, pasta_tasdrawpredictionpathcolorothers, 32768, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction path others color")

// Settings
MACRO_CONFIG_INT(PastaBalanceBot, pasta_balancebot, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Balance bot")
MACRO_CONFIG_INT(PastaHookSpam, pasta_hookspam, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook spam")
MACRO_CONFIG_INT(PastaPixelWalk, pasta_pixelwalk, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pixel walk")
MACRO_CONFIG_INT(PastaHookNearestCollisionAutoHook, pasta_hooknearestcollisionautohook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook nearest collision")
MACRO_CONFIG_INT(PastaHookRide, pasta_hookride, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook ride")
MACRO_CONFIG_INT(PastaPredictionTeleports, pasta_predictionteleports, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction teleports")
MACRO_CONFIG_INT(PastaPredictionAdvancedSettings, pasta_predictionadvancedsettings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction advanced settings")
MACRO_CONFIG_INT(PastaPredictionDeathTile, pasta_predictiondeathtile, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction death tile")
MACRO_CONFIG_INT(PastaPredictionMoveRestriction, pasta_predictionmoverestriction, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction move restriction")
MACRO_CONFIG_INT(PastaPredictionPlayers, pasta_predictionplayers, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction players")
MACRO_CONFIG_INT(PastaPredictionHeart, pasta_predictionheart, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Prediction heart")
MACRO_CONFIG_INT(PastaBalanceBotOffset, pasta_balancebot_offset, 2, 0, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Balance bot offset")
MACRO_CONFIG_INT(PastaHookNearestCollisionFov, pasta_hooknearestcollisionfov, 360, 1, 360, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook nearest collision fov")
MACRO_CONFIG_INT(PastaDiscordRpc, pasta_discordrpc, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Discord rpc")
MACRO_CONFIG_INT(PastaDiscordRpcMode, pasta_discordrpc_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Discord rpc mode")
MACRO_CONFIG_STR(PastaDiscordRpcIdCustom, pasta_discordrpc_id_custom, 64, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Discord rpc custom id")
